FROM golang:1.24 as builder

ARG TARGETOS
ARG TARGETARCH

USER 0
WORKDIR /app

COPY go.* ./
RUN go mod download

COPY ./cmd/consumer  ./cmd/consumer 
RUN CGO_ENABLED=0 GOOS=linux GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o main -v -mod=readonly ./cmd/consumer 

FROM alpine:3.22.2
COPY --from=builder /app/main /main
CMD ["/main"]