FROM golang:1.24.10-alpine3.21 as builder

ARG TARGETOS
ARG TARGETARCH

USER 0
WORKDIR /app

COPY go.* ./
RUN go mod download

COPY ./cmd/producer  ./cmd/producer
RUN CGO_ENABLED=0 GOOS=linux GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o main -v -mod=readonly ./cmd/producer 

FROM alpine:3.21
COPY --from=builder /app/main /main
CMD ["/main"]