# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: App-Go-Build-Test 

on:
  workflow_dispatch:  
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Go-Vet 
      run: go vet ./...
  
    - name: Go-Build
      run: go build -v ./...

    - name: Go-Test
      run: go test -v ./...
